#!/usr/bin/php
<?php
define('APP_PATH', __DIR__);
function app_path($path=null){
	return APP_PATH . $path;
}
function libs($path){
	return APP_PATH . '/_crystal' . $path;
}
include_once '_crystal/Console/handle.php';

